from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import Client
import Main


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setWindowIcon(QtGui.QIcon('favicon.png'))
        loginWindow.setObjectName("loginWindow")
        loginWindow.setFixedSize(324, 308)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setBold(True)
        font.setWeight(75)
        loginWindow.setFont(font)
        loginWindow.setStyleSheet("background-color: black")
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 258, 246))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet("QLabel{color:white}")
        self.verticalLayout.addWidget(self.label)
        self.usernameLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usernameLine.setStyleSheet("Username")
        self.usernameLine.setText("")
        self.usernameLine.setObjectName("usernameLine")
        self.usernameLine.setStyleSheet("QLineEdit{background-color: rgb(128, 128, 128); color: white}")
        self.verticalLayout.addWidget(self.usernameLine)
        self.passwordLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordLine.setAutoFillBackground(False)
        self.passwordLine.setStyleSheet("Password")
        self.passwordLine.setInputMask("")
        self.passwordLine.setText("")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setClearButtonEnabled(False)
        self.passwordLine.setObjectName("passwordLine")
        self.passwordLine.setStyleSheet("QLineEdit{background-color: rgb(128, 128, 128); color: white}")
        self.verticalLayout.addWidget(self.passwordLine)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.signInButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.signInButton.setEnabled(True)
        self.signInButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setBold(True)
        font.setWeight(75)
        self.signInButton.setFont(font)
        self.signInButton.setAutoDefault(False)
        self.signInButton.setObjectName("signInButton")
        self.signInButton.clicked.connect(self.userCredentials)
        self.signInButton.setStyleSheet("QPushButton{background-color: rgb(128, 128, 128); color: white}")
        self.signInButton.setDefault(True)
        self.verticalLayout.addWidget(self.signInButton)
        self.exitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.exitButton.setStyleSheet("QPushButton{background-color: rgb(128, 128, 128); color: white}")
        self.exitButton.setDefault(True)
        self.exitButton.clicked.connect(lambda: loginWindow.close())
        self.verticalLayout.addWidget(self.exitButton)
        loginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Login"))
        self.label.setText(_translate("loginWindow", "LOGIN"))
        self.usernameLine.setPlaceholderText(_translate("loginWindow", "Username"))
        self.passwordLine.setPlaceholderText(_translate("loginWindow", "Password"))
        self.signInButton.setText(_translate("loginWindow", "Sign in"))
        self.exitButton.setText(_translate("loginWindow", "Exit"))

    def userCredentials(self):
        userUsername = self.usernameLine.text()
        userPassword = self.passwordLine.text()

        if not userPassword or not userUsername:
            self.warningBox("missing")

        # elif KOMBINACE JMÉNA A HESLA JE NESPRÁVNÁ: self.warningBox("wrong")
        # Dopsat kód na předání údajů
        else:
            print(f"Username: {userUsername}\nPassword: {userPassword}")
            self.MainWindow = QtWidgets.QMainWindow()
            self.ui = Main.Ui_mainWindow()
            self.ui.setupUi(self.MainWindow)
            self.MainWindow.show()
            self.exitButton.click()

    def warningBox(self, reason):
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setBold(True)
        font.setWeight(600)
        font.setPointSize(11)
        msg = QMessageBox()
        msg.setWindowIcon(QtGui.QIcon('favicon.png'))
        msg.setStyleSheet("background-color: black; color: white")
        msg.setFont(font)
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Warning)
        msg.setDefaultButton(QtWidgets.QPushButton())
        if reason == "missing":
            msg.setText("Username or password missing!")
        elif reason == "wrong":
            msg.setText("Wrong username or password!")
        msg.exec_()
